/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<'Root', '/', Record<never, never>, Record<never, never>>,
    '$Path': RouteRecordInfo<'$Path', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    'DemoKeepalive': RouteRecordInfo<'DemoKeepalive', '/demo/keepalive', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'User': RouteRecordInfo<'User', '/user', Record<never, never>, Record<never, never>>,
  }
}
